call plug#begin()
Plug 'fatih/vim-go'
Plug 'godlygeek/tabular'
Plug 'morhetz/gruvbox'
Plug 'powerman/vim-plugin-AnsiEsc'
Plug 'preservim/vim-markdown'
Plug 'tpope/vim-sensible'
call plug#end()

set background=dark
set viminfo+=n~/.vim/viminfo
colorscheme gruvbox

" disable folding for markdown files
let g:vim_markdown_folding_disabled = 1

" Use a bar cursor when in insert mode and block cursor everywhere else
"
" Reference char of values
" Ps = 0 blinking block
" Ps = 1 blinking block (default).
" Ps = 2 steady block
" Ps = 3 blinking underline
" Ps = 4 steady underline
" Ps = 5 blnking bar
" Ps = 6 steady bar
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

if has('gui_running')
	set guifont=Inconsolata-Regular:h16
	set guioptions=aegm
endif
